openapi: 3.0.0
info:
  version: 1.0.0
  title: Test API
paths:
  "/pet/{petId}":
    post:
      tags:
        - pet
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - name
              properties:
                id:
                  type: integer
                  format: int64
                  readOnly: true
                  default: 40
                  example: 25
                name:
                  type: string
                  example: doggie
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - name
                properties:
                  id:
                    type: integer
                    format: int64
                    default: 40
                    example: 25
                  name:
                    type: string
                    example: doggie
